[SERVICE]
    Flush        1
    Log_Level    trace
    Daemon       Off
    Parsers_File ./parsers.conf

[INPUT]
    Name             tail
    Path             /var/log/test_rewritetfb.log
    Tag              raw.logs
    Read_from_Head   true

[FILTER]
    Name     parser
    Match    raw.logs
    Key_Name message
    Parser   json_parser

[FILTER]
    Name    rewrite_tag
    Match   raw.logs
    Rule    $service ^(.*)$ logs.$TAG.$service true

[FILTER]
    Name    record_modifier
    Match   logs.*.payment
    Record  oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.phx.amaaaaaaidfzkvqanxgjvto2ixyjh7ui27imndufy5t7qgvqml5hzcs7ianq
    Record  oci_la_log_source_name  fb_testing_src_1

[FILTER]
    Name    record_modifier
    Match   logs.*.user
    Record  oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.phx.amaaaaaaidfzkvqanxgjvto2ixyjh7ui27imndufy5t7qgvqml5hzcs7ianq
    Record  oci_la_log_source_name fb_testing_src_2

[FILTER]
    Name    record_modifier
    Match   logs.*.order
    Record  oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.phx.amaaaaaaidfzkvqanxgjvto2ixyjh7ui27imndufy5t7qgvqml5hzcs7ianq
    Record  oci_la_log_source_name fb_testing_src_3

[FILTER]
    Name    record_modifier
    Match   logs.*.inventory
    Record  oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.phx.amaaaaaaidfzkvqanxgjvto2ixyjh7ui27imndufy5t7qgvqml5hzcs7ianq
    Record  oci_la_log_source_name fb_testing_src_4

[FILTER]
    Name    record_modifier
    Match   logs.*
    Record  oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.phx.amaaaaaaidfzkvqanxgjvto2ixyjh7ui27imndufy5t7qgvqml5hzcs7ianq
    Record  oci_la_log_source_name reda_log_source_testing

[OUTPUT]
    Name                     oracle_log_analytics
    Match                    logs.*
    auth_type               config_file
    config_file_location    /home/opc/.oci/config
    profile_name            DEFAULT
    namespace               ax1zffkcg1fy
    oci_config_in_record    true
    TLS                     On
    tls.verify              On
