[SERVICE]
  flush 5
  daemon Off
  log_level debug
[INPUT]
  Name tail
  Tag oci.syslog.log
  Path  /Users/v618061/Work/fluent-bit/data/linuxsyslog.log
  Read_From_Head True
[FILTER]
  Name record_modifier
  Match oci.syslog.log
  Record oci_la_log_path /Users/v618061/Work/fluent-bit/data/linuxsyslog_2.log
  Record oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.iad.amaaaaaayd2l6zya2csvhwsrw4hg377vjsd2mazvcxn5wcx5fokb36askuyq
[INPUT]
  Name  tail
  Tag  oci.cronlogs.log
  Path  /Users/v618061/Work/fluent-bit/data/cronlog.log
  Read_From_Head True
[FILTER]
  Name record_modifier
  Match oci.cronlogs.log
  Record oci_la_log_source_name LinuxCronLogSource
  Record oci_la_log_path /Users/v618061/Work/fluent-bit/data/cronlog_2.log
  Record oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.iad.amaaaaaayd2l6zyayicet33gcbhpemjzu7n6kuzgfiqfrsd3kwpn755heiiq

[INPUT]
  Name  tail
  Tag  oci.yumlogs.log
  Path  /Users/v618061/Work/fluent-bit/data/yumlog.log
  Read_From_Head True
[FILTER]
  Name record_modifier
  Match oci.yumlogs.log
  Record oci_la_log_source_name LinuxYUMLogSource
  Record oci_la_log_path /Users/v618061/Work/fluent-bit/data/yumlog_2.log
  Record oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.iad.amaaaaaayd2l6zyayicet33gcbhpemjzu7n6kuzgfiqfrsd3kwpn755heiiq

[FILTER]
  Name record_modifier
  Match oci.*
  Record oci_la_log_source_name LinuxSyslogSource
[Output]
  Name oracle_log_analytics
  Match *
  host loganalytics-stage.us-ashburn-1.oci.oraclecloud.com
  Namespace idycimrilmf8
  config_file_location /Users/v618061/Work/fluent-bit/oci-config/config
  profile_name DEFAULT
  oci_config_in_record true
  tls On
  tls.verify Off