[SERVICE]
    flush 1
    daemon Off
    log_level trace
[INPUT]
    Name         tail
    path         /var/log/dummy.log
    Tag          remote_vm_logs
    Read_from_Head  true 

[OUTPUT]
    Name oracle_log_analytics
    Match *
    auth_type instance_principal
    config_file_location /home/opc/.oci/config
    profile_name DEFAULT
    namespace ax1zffkcg1fy
    oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.phx.amaaaaaaidfzkvqanxgjvto2ixyjh7ui27imndufy5t7qgvqml5hzcs7ianq
    oci_la_log_source_name reda_log_source_testing
    TLS On
    tls.verify On
