[SERVICE]
    flush 15
    daemon Off
    log_level debug
    Parsers_File /Users/v618061/Work/fluent-bit/conf/confluence/json_parsers.conf
[INPUT]
    Name tail
    Tag  k8s_job_logs_tag
    Path  /Users/v618061/Work/fluent-bit/data/k8sjoblog.log
    Parser k8s_job_logs
    Read_From_Head True
[Output]
    Name oracle_log_analytics
    Match *
    host loganalytics-stage.us-ashburn-1.oci.oraclecloud.com
    Namespace idycimrilmf8
    config_file_location /Users/v618061/Work/fluent-bit/oci-config/config
    profile_name DEFAULT
    oci_la_log_source_name ociK8sJobobjLogSource
    oci_la_log_group_id ocid1.loganalyticsloggroup.oc1.iad.amaaaaaayd2l6zyaxnzyefc74aao25x2psssp7dqtskxy72bijwfelrucwxq
    oci_la_log_path /Users/v618061/Work/fluent-bit/data/k8sjoblog_17july2025.log
    tls On
    tls.verify Off